export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';


export const SIGN_USER = 'SIGN_USER';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_FAILURE = 'SIGN_USER_FAILURE';


export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS';
export const GET_ALL_RECIPES_FAILURE = 'GET_ALL_RECIPES_FAILURE';


export const GET_POPULAR_RECIPES = 'GET_POPULAR_RECIPES';
export const GET_POPULAR_RECIPES_SUCCESS = 'GET_POPULAR_RECIPES_SUCCESS';
export const GET_POPULAR_RECIPES_FAILURE = 'GET_POPULAR_RECIPES_FAILURE';

export const GET_RECIPE_DATA = 'GET_RECIPE_DATA';
export const GET_RECIPE_DATA_SUCCESS = 'GET_RECIPE_DATA_SUCCESS';
export const GET_RECIPE_DATA_FAILURE = 'GET_RECIPE_DATA_FAILURE';

export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const VOTE_A_RECIPE_SUCCESS = 'VOTE_A_RECIPE_SUCCESS';
export const VOTE_A_RECIPE_FAILURE = 'VOTE_A_RECIPE_FAILURE';

export const FAVORITE_RECIPE_SUCCESS = 'FAVORITE_RECIPE_SUCCESS';
export const FAVORITE_RECIPE_FAILURE = 'FAVORITE_RECIPE_FAILURE';

export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const GET_USER_RECIPES_SUCCESS = 'GET_USER_RECIPES_SUCCESS';
export const GET_USER_RECIPES_FAILURE = 'GET_USER_RECIPES_FAILURE';

export const GET_USER_FAVORITE_RECIPE = 'GET_USER_FAVORITE_RECIPE';
export const GET_USER_FAVORITE_RECIPE_SUCCESS = 'GET_USER_FAVORITE_RECIPE_SUCCESS';
export const GET_USER_FAVORITE_RECIPE_FAILURE = 'GET_USER_FAVORITE_RECIPE_FAILURE';

export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = ' GET_USER_DATA_FAILURE';

export const GET_USER_FAVORITE_RECIPE_IDS = 'GET_USER_FAVORITE_RECIPE_IDS';
export const GET_USER_FAVORITE_RECIPE_IDS_FAILURE = 'GET_USER_FAVORITE_RECIPE_IDS_FAILURE';

export const FAVORITE_A_RECIPE_SUCCESS = 'FAVORITE_A_RECIPE_SUCCESS';
export const FAVORITE_A_RECIPE_FAILURE = 'FAVORITE_A_RECIPE_FAILURE';

export const VOTE_RECIPE = 'VOTE_RECIPE';

export const CHANGE_USER_AUTH = 'CHANGE_USER_AUTH';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const RESET_USER_ERROR = 'RESET_USER_ERROR';
export const RESET_REVIEW_ERROR = 'RESET_REVIEW_ERROR';

export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';
