export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';


export const SIGN_USER = 'SIGN_USER';
export const SIGN_USER_SUCCESS = 'SIGN_USER_SUCCESS';
export const SIGN_USER_FAILURE = 'SIGN_USER_FAILURE';


export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS';
export const GET_ALL_RECIPES_FAILURE = 'GET_ALL_RECIPES_FAILURE';


export const GET_POPULAR_RECIPES = 'GET_POPULAR_RECIPES';
export const GET_POPULAR_RECIPES_SUCCESS = 'GET_POPULAR_RECIPES_SUCCESS';
export const GET_POPULAR_RECIPES_FAILURE = 'GET_POPULAR_RECIPES_FAILURE';


export const VOTE_RECIPE = 'VOTE_RECIPE';

export const CHANGE_USER_AUTH = 'CHANGE_USER_AUTH';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const EDIT_RECIPE = 'EDIT_RECIPE';
export const GET_RECIPE_DATA = 'GET_RECIPE_DATA';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const RESET_USER_ERROR = 'RESET_USER_ERROR';
